title: "Site title" # _data/site-text.yml
description: "Site description" # _data/site-text.yml
email: "webmaster@wgdd.org"

markdown: kramdown

defaults:
  #languages
  - scope:
      path: ""
    values:
      lang: "en"
      layout: default
  - scope:
      path: "de"
    values:
      lang: "de"
  - scope:
      path: "it"
    values:
      lang: "it"

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

# vim: set tw=79 ts=2 sw=2 ai si et:
