title: "Site title" # _data/site-text.yml
description: "Site description" # _data/site-text.yml

url:  # hostname & protocol of the site
baseurl: # subpath of the site
repository: # GitHub username/repository

email: "webmaster@wgdd.org"
locales:
  - en
  - de
  - it

markdown: kramdown

defaults:
  #languages
  - scope:
      path: ""
    values:
      lang: "en"
      locale: "en-US"
      layout: default
      permalink: /:path/:basename/
  - scope:
      path: "de"
    values:
      lang: "de"
      locale: "de-DE"
  - scope:
      path: "it"
    values:
      lang: "it"
      locale: "it-IT"
  - scope:
      path: ""
      type: posts
    values:
      permalink: /en/:year/:month/:title/
  - scope:
      path: "de"
      type: posts
    values:
      permalink: /de/:year/:month/:title/
  - scope:
      path: "it"
      type: posts
    values:
      permalink: /it/:year/:month/:title/

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

# vim: set tw=79 ts=2 sw=2 ai si et:
