title: "Site title" # _data/site-text.yml
description: "Site description" # _data/site-text.yml

url:  # hostname & protocol of the site
baseurl: # subpath of the site
repository: # GitHub username/repository

email: "webmaster@wgdd.org"
locales:
  - en
  - de
  - it

markdown: kramdown

collections:
  pages:
    output: true
  debian:
    output: true    

defaults:
  #languages
  - scope:
      path: ""
    values:
      lang: "en"
      locale: "en-US"
      layout: default
  - scope:
      path: "*/de"
    values:
      lang: "de"
      locale: "de-DE"
  - scope:
      path: "*/it"
    values:
      lang: "it"
      locale: "it-IT"
  # posts      
  - scope:
      path: ""
      type: posts
    values:
      permalink: /en/:year/:month/:title/
  - scope:
      path: "_posts/de"
      type: posts
    values:
      permalink: /de/:year/:month/:title/
  - scope:
      path: "_posts/it"
      type: posts
    values:
      permalink: /it/:year/:month/:title/
  # pages
  - scope:
      path: ""
      type: pages
    values:
      permalink: /:path/
  # collections
  - scope:
     path: ""
     type:
        - debian
    values:
      permalink: /en/:collection/:name/
  - scope:
      path: "*/de"
      type:
        - debian
    values:
      permalink: /de/:collection/:name/
  - scope:
      path: "*/it"
      type:
        - debian
    values:
      permalink: /it/:collection/:name/

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

# vim: set tw=79 ts=2 sw=2 ai si et:
